### ISSUE TITLE
Update repo description

### ISSUE THREAD

**Issue by luckyshot** [greduan/chrome-ext-tabulator#2]
The `greduan` branch now has the latest changes of `luckyshot`.

Just one thing left to do @greduan , as the owner you need to update the project description from:

> Like OneTab but leaner and FOSS - UNMAINTAINED, SEE README

to:

> Tabulator is a free Google Chrome extension that helps reduce tab clutter and memory usage by saving all your open tabs into lists which can be restored at another time

But please, there's no hurry... Enjoy your holidays and we'll catch up when you get back! 🏖

**Comment by greduan** [comment]
This has been done now :slightly_smiling_face:
